# Homebrew formula for the tap `Na5co/homebrew-tap` (brew install na5co/tap/polygo).
# Generated by scripts/formula.sh from the release's SHA256SUMS; do not edit by hand.
class Polygo < Formula
  desc "Translate app strings (xcstrings, Android, ARB, i18next, po, resx) via local LLM"
  homepage "https://github.com/Na5co/polygo"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-darwin.tar.gz"
      sha256 "bf294793221e5a1ec264f92fc3168195f29d4fe96f054ca308c83dad85d3ea97"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-darwin.tar.gz"
      sha256 "f7d22ea91438d9aec2ee32fb7fea75dbb859bc2b2bec1ca4ad53a55201b6ddf6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-linux.tar.gz"
      sha256 "8e6322f0b04df9e289aff137a29db9c75e156d1419cb519908329c99cef557ad"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-linux.tar.gz"
      sha256 "411a427cce31477cfd09bc1c87864b0e0041d617e466edddf25007c4847dcab6"
    end
  end

  def install
    bin.install "polygo"
    generate_completions_from_executable(bin/"polygo", "completions")
  end

  test do
    assert_match "polygo", shell_output("#{bin}/polygo --version")
  end
end
