# Homebrew formula for the tap `Na5co/homebrew-tap` (brew install na5co/tap/polygo).
# Generated by scripts/formula.sh from the release's SHA256SUMS; do not edit by hand.
class Polygo < Formula
  desc "Translate app strings (xcstrings, Android, ARB, i18next, po, resx) via local LLM"
  homepage "https://github.com/Na5co/polygo"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-darwin.tar.gz"
      sha256 "849ce98076fd34b98e6c5f5be8fde46f9e26c5f258435551c858b85a99e32efe"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-darwin.tar.gz"
      sha256 "881593eef30fca60d3c9d217f60679d90719bc8f58b00ffb6cb429e93115f214"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-linux.tar.gz"
      sha256 "a68e022b5e508260c6c47f47aa4ef32fbe9ef0d4844738d2f74085d85427e2df"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-linux.tar.gz"
      sha256 "5d1328c786915ab2d793101ca956f64594bc80919c0806917b604995daa04f06"
    end
  end

  def install
    bin.install "polygo"
    generate_completions_from_executable(bin/"polygo", "completions")
  end

  test do
    assert_match "polygo", shell_output("#{bin}/polygo --version")
  end
end
