# Homebrew formula for the tap `Na5co/homebrew-tap` (brew install na5co/tap/polygo).
# Generated by scripts/formula.sh from the release's SHA256SUMS; do not edit by hand.
class Polygo < Formula
  desc "Translate app strings (xcstrings, Android, ARB, i18next, po, resx) via local LLM"
  homepage "https://github.com/Na5co/polygo"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-darwin.tar.gz"
      sha256 "768e4497e8b28069877f34527a1d28f20214375e8f619be0acec2756e9c2cce0"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-darwin.tar.gz"
      sha256 "3a830a30556027fb91b816580e4f6cfe5bb14e683b27f7073201a85a3b27d1ec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-aarch64-linux.tar.gz"
      sha256 "4bce9c7875c632e569ac5a69e3da6b11affa1b977a625f19ef5b1a84b1fbf27a"
    end
    on_intel do
      url "https://github.com/Na5co/polygo/releases/download/v#{version}/polygo-v#{version}-x86_64-linux.tar.gz"
      sha256 "8ab4f247795404dc5f9e6cd3ebb41b91a61e8a47e72d62c3e00b120f56db75df"
    end
  end

  def install
    bin.install "polygo"
    generate_completions_from_executable(bin/"polygo", "completions")
  end

  test do
    assert_match "polygo", shell_output("#{bin}/polygo --version")
  end
end
